name: Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test Action
      run: |
        echo "✅ GitHub Actions is working!"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref }}"